### ISSUE TITLE
Compile error on linux. Old version of libsodium(1.06).

### ISSUE THREAD

**Issue by altcoinpirate** [PirateNetwork/SevenSeas#1]
When I  compile on debian, ./build.sh creates an error when /res/libsodium/buildlibsodium.sh attempts to download libsodium, returning:

```
--2020-03-12 14:31:40--  https://download.libsodium.org/libsodium/releases/libsodium-1.0.16.tar.gz

Resolving download.libsodium.org (download.libsodium.org)... 37.59.238.213
Connecting to download.libsodium.org (download.libsodium.org)|37.59.238.213|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-03-12 14:31:43 ERROR 404: Not Found.

tar: libsodium-1.0.16.tar.gz: Cannot open: No such file or directory
```
Visiting the download location shows that [https://download.libsodium.org/libsodium/releases/libsodium-1.0.16.tar.gz](https://download.libsodium.org/libsodium/releases/libsodium-1.0.16.tar.gz) does not exist.
It has been moved to:
[https://download.libsodium.org/libsodium/releases/old/libsodium-1.0.16.tar.gz](https://download.libsodium.org/libsodium/releases/old/libsodium-1.0.16.tar.gz)
and replaced with 1.07 and 1.08, resulting in the 404 error.

**Comment by TheComputerGenie** [comment]
fixed with https://github.com/PirateNetwork/SevenSeas/commit/7267f7cd00feb57059f3d4d200ef246cd75424dc
